name: Toma Toe Workflow
on: [push]

jobs:
  publish-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile infrastructure
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az bicep build --file ./deployment/main.bicep
      - name: Compile infrastructure
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az bicep build --file ./deployment/trafficmgr.bicep
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bicep-templates
          path: deployment/*.json

  infrastructure-incremental-test:
    needs: publish-bicep
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bicep-templates
          path: ./infrastructure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_TEST }}
      - name: Deploy Infrastructure
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az deployment sub create --location westeurope --template-file ./infrastructure/main.json --parameters ./infrastructure/test.parameters.json

  infrastructure-incremental-prod:
    needs: infrastructure-incremental-test
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bicep-templates
          path: ./infrastructure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_TEST }}
      - name: Deploy Infrastructure
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az deployment sub create --location westeurope --template-file ./infrastructure/main.json --parameters ./infrastructure/test.parameters.json
